# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='question',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
